# Generated by Django 5.0.6 on 2024-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBakso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('isi_porsi', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
