# Generated by Django 5.0.6 on 2024-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinumanPojokJoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
