# Generated by Django 5.0.6 on 2024-05-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0002_minumanpojokjoyo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('meja', models.CharField(max_length=100)),
                ('pesanan', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Diantar Ke Meja', 'Diantar Ke Meja'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Diantar Ke Meja', max_length=20)),
            ],
        ),
    ]
