# Generated by Django 5.0.6 on 2024-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0003_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='status',
            field=models.CharField(choices=[('Sedang Diproses', 'Sedang Diproses'), ('Diantar Ke Meja', 'Diantar Ke Meja'), ('Proses Bungkus Selesai', 'Proses Bungkus Selesai'), ('Bersihkan Meja!', 'Bersihkan Meja!'), ('Done', 'Done')], default='Sedang Diproses', max_length=25),
        ),
    ]
