# Generated by Django 5.0.6 on 2024-05-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0004_alter_orderlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
