# Generated by Django 5.0.6 on 2024-05-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0005_orderlist_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorsiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kuah', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('lainnya', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porsi_details', to='ordersystem_app.orderlist')),
            ],
        ),
    ]
