# Generated by Django 5.0.6 on 2024-05-18 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0006_porsidetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porsidetail',
            name='detail',
        ),
        migrations.AddField(
            model_name='porsidetail',
            name='details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
