# Generated by Django 5.0.6 on 2024-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0007_remove_porsidetail_detail_porsidetail_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='pesanan',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='pilihan',
            field=models.CharField(default='makan_sini', max_length=50),
        ),
    ]
