# Generated by Django 5.0.6 on 2024-05-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem_app', '0008_remove_orderlist_detail_remove_orderlist_pesanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porsidetail',
            name='details',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
